// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TarefasApi.Data;

#nullable disable

namespace TarefasApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241114005708_Usuario")]
    partial class Usuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TarefasApi.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_CATEGORIAS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Matematica"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Fisica"
                        });
                });

            modelBuilder.Entity("TarefasApi.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<bool>("Completo")
                        .HasColumnType("bit");

                    b.Property<string>("DataTermino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("TB_TAREFAS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Completo = false,
                            DataTermino = "05/10",
                            Nome = "Estudar Matemática",
                            Prioridade = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Completo = false,
                            DataTermino = "11/10",
                            Nome = "Revisar Física",
                            Prioridade = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Completo = false,
                            DataTermino = "28/11",
                            Nome = "Regra de três",
                            Prioridade = 0
                        });
                });

            modelBuilder.Entity("TarefasApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "seuEmail@gmail.com",
                            Latitude = -23.520024100000001,
                            Longitude = -46.596497999999997,
                            Nome = "UsuarioAdmin",
                            PasswordHash = new byte[] { 29, 98, 110, 151, 117, 3, 172, 241, 204, 175, 115, 211, 84, 242, 148, 104, 157, 116, 56, 210, 19, 85, 194, 41, 30, 243, 33, 234, 228, 28, 176, 143, 48, 217, 167, 149, 180, 238, 12, 11, 225, 152, 225, 169, 0, 188, 31, 220, 146, 7, 119, 105, 91, 86, 245, 3, 227, 199, 41, 86, 223, 149, 166, 236 },
                            PasswordSalt = new byte[] { 80, 24, 103, 88, 105, 154, 47, 223, 178, 134, 185, 104, 25, 252, 145, 138, 70, 100, 93, 78, 85, 126, 86, 240, 18, 36, 26, 65, 189, 237, 104, 155, 232, 65, 197, 12, 56, 126, 170, 108, 135, 226, 44, 38, 183, 95, 137, 4, 158, 208, 178, 239, 66, 108, 70, 13, 94, 156, 218, 180, 181, 196, 212, 30, 173, 59, 127, 50, 18, 193, 83, 17, 148, 12, 77, 29, 112, 23, 171, 68, 21, 2, 152, 215, 190, 15, 201, 240, 35, 108, 156, 160, 141, 29, 85, 57, 179, 224, 4, 86, 135, 67, 219, 63, 25, 226, 117, 42, 197, 135, 123, 176, 231, 142, 115, 247, 160, 66, 163, 252, 229, 87, 78, 109, 76, 59, 61, 35 },
                            Perfil = "Admin"
                        });
                });

            modelBuilder.Entity("TarefasApi.Models.Categoria", b =>
                {
                    b.HasOne("TarefasApi.Models.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TarefasApi.Models.Tarefa", b =>
                {
                    b.HasOne("TarefasApi.Models.Categoria", "Categoria")
                        .WithMany("Tarefas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TarefasApi.Models.Categoria", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("TarefasApi.Models.Usuario", b =>
                {
                    b.Navigation("Categorias");
                });
#pragma warning restore 612, 618
        }
    }
}
